#! /bin/bash
TOKEN=$(gh auth token)
USER=${1:?Needs to specify user}
curl -H "Authorization: Bearer ${TOKEN}" \
  -v "https://github.com/api/v3/users/${USER}/repos?type=fork&per_page=100&page=1" \
| jq -r '.[].name' >> out

awk '{print "${USER}/" $0}' ./out > ./to-delete
for repo in $(<to-delete); 
  do curl -H "Authorization: Bearer ${TOKEN}" -X DELETE "https://github.com/api/v3/repos/$repo" ; 
  sleep 0.5; 
done
