#! /bin/bash
  2
  3 USER=${USER:?Needs to specify user}
  4 HOSTNAME=${HOSTNAME:?Need to define a hostname}
  5 TOKEN=$(gh auth token -h $HOSTNAME)
  6 curl -L \
  7   -H "Authorization: Bearer ${TOKEN}" \
  8   -H "X-GitHub-Api-Version: 2022-11-28"\
  9   -H "Accept: application/vnd.github+json" \
 10   -v "https://api.github.com/orgs/${USER}/repos?type=fork&per_page=100&page=1" \
 11 >> out
 12 #| jq -r '.[].name' >> out
 13
 14 awk '{print "${USER}/" $0}' ./out > ./to-delete
